# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cdfc7c1f15dafad5b6f6925d4a704bfa3e18b4acf5f31137e9ea8678d94513db1510f435d65aba3f69f3b0895116c3136b1df25ef74ec6142725418043497ac

test:
  secret_key_base: 55e6d162937ac714c38be1e72454b0d7390f6627c3713ee661a7833bb63ab9461068d6cbd79dcc451b45ef9b07c357cc73d404b0c55c4de412dea9197bbd6a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
